name: Check Links

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 1'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: Build docs
        run: mkdocs build

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --verbose
            --no-progress
            --exclude 'fonts.gstatic.com'
            --exclude 'mahimathacker.github.io'
            './site/**/*.html'
          fail: true